version: '3.3'

services:

  solr:
    container_name: tml_solr
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - articles
      
  db:
    container_name: tml_pg
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - pg_data:/var/lib/postgresql/data

  transmedialint:
    build: .
    restart: always
    command: "/transmedialint/run.sh"
    ports:
      - "8000:8000"
      - "6800:6800"
    environment:
      - DB_HOST=db
      - SOLR_HOST=solr
      - GUARDIAN_KEY=$GUARDIAN_KEY
      - TIMES_USERNAME=$TIMES_USERNAME
      - TIMES_PASSWORD=$TIMES_PASSWORD
      - TELEGRAPH_USERNAME=$TELEGRAPH_USERNAME
      - TELEGRAPH_PASSWORD=$TELEGRAPH_PASSWORD
    volumes:
      - tml_articles:/transmedialint/article_dump
      - tml_models:/transmedialint/model_dump
      - /dev/shm:/dev/shm
    depends_on:
      - solr
      - db

volumes:
  solr_data:
  pg_data:
  tml_articles:
  tml_models:

  
