version: '2'

services:

  solr:
    container_name: tml_solr
    image: solr:alpine
    ports:
     - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - articles
      
  db:
    container_name: tml_pg
    image: postgres
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - pg_data:/var/lib/postgresql/data

  splash:     
     container_name: tml_splash
     image: scrapinghub/splash
     ports:
      - 5023:5023
      - 8050:8050
      - 8051:8051

  transmedialint:
    build: .
    command: "/transmedialint/run.sh"
    ports:
      - "8000:8000"
      - "6800:6800"
    environment:
      - DB_HOST=db
      - SOLR_HOST=solr
      - GUARDIAN_KEY=$GUARDIAN_KEY
      - TIMES_USERNAME=$TIMES_USERNAME
      - TIMES_PASSWORD=$TIMES_PASSWORD
    volumes:
      - tml_articles:/transmedialint/article_dump
      - tml_models:/transmedialint/model_dump
    depends_on:
      - solr
      - db
      - splash

volumes:
  solr_data:
  pg_data:
  tml_articles:
  tml_models:

  
