version: '2'
services:
  solr:
    container_name: tml_solr
    image: solr:alpine
    ports:
     - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - articles
  db:
    container_name: tml_pg
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - pg_data:/var/lib/postgresql/data
      
volumes:
  solr_data:
  pg_data: