version: '2'

services:

  solr:
    container_name: tml_solr
    image: solr:alpine
    ports:
     - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - articles
      
  db:
    container_name: tml_pg
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - pg_data:/var/lib/postgresql/data
    
  scraper:
     build:
       dockerfile: ScraperDockerfile
       context: .
     ports:
       - "6800:6800"
     environment:
      - DB_HOST=db
     volumes:
      - tml_articles:/transmedialint/article_dump
      - tml_models:/transmedialint/model_dump     
     depends_on:
      - solr
      - db
     
  transmedialint:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    volumes:
      - tml_articles:/transmedialint/article_dump
      - tml_models:/transmedialint/model_dump
    depends_on:
      - solr
      - db
      - scraper
      
volumes:
  solr_data:
  pg_data:
  tml_articles:
  tml_models: