# Generated by Django 4.0.3 on 2022-03-14 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NamedEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('label', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddConstraint(
            model_name='namedentity',
            constraint=models.UniqueConstraint(fields=('text', 'label'), name='unique entities'),
        ),
        migrations.AddField(
            model_name='articleentity',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.article'),
        ),
        migrations.AddField(
            model_name='articleentity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tml_corpus.namedentity'),
        ),
    ]
