# Generated by Django 4.0.6 on 2022-07-25 01:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import sources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=32)),
                ('last_scraped', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256, unique=True)),
                ('slug', models.SlugField(max_length=256)),
                ('date_published', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('date_retrieved', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('content', models.FileField(upload_to=sources.models.content_directory_path)),
                ('preview', models.FileField(null=True, upload_to=sources.models.preview_directory_path)),
                ('raw', models.FileField(upload_to=sources.models.raw_directory_path)),
                ('broken', models.BooleanField(default=False)),
                ('author', models.ManyToManyField(to='sources.author')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
            options={
                'ordering': ('-date_published',),
            },
        ),
    ]
